"""add source to documents

Revision ID: eae103efba7f
Revises: ed954057da84
Create Date: 2026-04-02 17:44:34.555966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae103efba7f'
down_revision: Union[str, Sequence[str], None] = 'ed954057da84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(length=20), nullable=False, server_default='adilet'))
    op.alter_column('documents', 'source', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
